### ISSUE TITLE
Final Paper

### ISSUE THREAD

**Issue by Nikki-Luoma** [Nikki-Luoma/Nikki-Luoma.github.io#20]
In the first paragraph you have, " use ad blocker" it should be "use an ad blocker".
In the second paragraph "cyber bullying" should be "cyberbullying".
In the fourth paragraph, you have, "high speed" it should be "high-speed". You also have "hardly make money", it should be "hardly makes money".
In the fifth paragraph, you have, ". In order to counter this some websites are able to detect when use..", it should be, ". In order to counter this, some websites are able to detect when use".
In the sixth paragraph, you have, "new digital age", it should be, "new digital age,".
In the sixth paragraph, you have, "are non existent", it should be, "are nonexistent".
In the sixth paragraph, you have, "have better written", it should be, "have better-written".

**Comment by nadeld** [comment]
Is cyber bullying one word? I think it should be cyberbullying
This sentence could be changed. Despite cyber bullying having the same effect as regular bullying, some states do not have laws or bullying policies that protect the victim when they are off campus, for example online. Maybe say online makes it difficult to enforce bullying policies.
"Stop bullying.gov" - should be one word.
"which shows there are not consequences for cyber bullying." which shows that the state does not have any consequences for cyberbullying.
"In the last decade about 34% of students considered plagiarism a serious crime but more recently this number has dropped to 29%. " - citation after this? 
"unless the students"- unless students
"Although this sounds like a server punishment"- severe punishment
"Now that most people have high speed internet they are able to get whatever content that they want at their fingertips for free. - Now that many people have high-speed internet, people can get access to content easier than ever before.
"It can also be argued that piracy hurts musicians, but artist hardly make money off of their song purchases and streams." - I feel this is unneeded since you do not elaborate on it
" use advertisements revenue" -use revenue from ads
"In 2015" -In 2015,
"In order to counter this some websites are able to detect when users are using an ad blocker and have been either telling users that this is hurting their ad revenue and asking them to disable the ad blocker, or the websites are forcing users to stop using their ad blocker in order to continue viewing the website. " - consider shortening this sentence
"Although most people do not do this because other than morals there is not a real reason to." -do not end a sentence with a preposition
"The reason that piracy, plagiarism, cyber bullying and the loss of ad revenue exists because of laws that are non existent or not enforced." - are because of
"Although people should do the right thing despite internet anonymity a solution to these problems is to have better written laws and to enforce them even more." - , after anonymity
" is to education the people and truly have the majority of internet users against these crimes." - is to educate the people

**Comment by Nikki-Luoma** [comment]
Thank You
